### ISSUE TITLE
Missing DB_GENECARDS_GENE_DISEASE_SCORE file?

### ISSUE THREAD

**Issue by davetang** [WGLab/phenolyzer#1]
When running the example from README.md:

`perl disease_annotation.pl alzheimer -p -ph -logistic -out out/alzheimer_addon_all/out -addon DB_DISGENET_GENE_DISEASE_SCORE,DB_GAD_GENE_DISEASE_SCORE,DB_GENECARDS_GENE_DISEASE_SCORE -addon_weight 0.25`

I get the error:

`could not open ./lib/compiled_database/DB_GENECARDS_GENE_DISEASE_SCORE at disease_annotation.pl line 655.`

Perhaps the script `integrate_genecards_gene_disease.pl` is used to generate DB_GENECARDS_GENE_DISEASE_SCORE but it requires the file `raw_gene_cards`, which according to the script should be in the `lib` directory but is also missing.

May you provide the DB_GENECARDS_GENE_DISEASE_SCORE file or let me know how I can generate it?

Thanks

**Comment by kaichop** [comment]
Please remove DB_GENECARDS_GENE_DISEASE_SCORE from command line. We cannot
provide it in the website to avoid copyright issues (but you may get the
file yourself from genecards).

**Comment by davetang** [comment]
Is the `raw_gene_cards` file simply the list of genes from GeneCards' Genes Associated with Diseases?

Line 11 of `integrate_genecards_gene_disease.pl`:

```
my ($gene, $name,$locus,$disease) = split(/\t+/,$line);
```

does match the GeneCards' Genes Associated with Diseases table:

![screen shot 2016-03-22 at 1 53 48 pm](https://cloud.githubusercontent.com/assets/2980289/13943205/914a90d6-f035-11e5-8a6e-f242f6a9e584.png)
