### ISSUE TITLE
Rcpp.so,slam.so,wordcloud.so for ARM

### ISSUE THREAD

**Issue by haileeshen** [WGLab/phenolyzer#11]
Hello team,
Can you  provide the source code of the embedded  .SO libs (Rcpp.so,slam.so,wordcloud.so),?Because I want run phenlolyzer on my ARM Server

**Comment by kaichop** [comment]
These are standard R libraries that you can just install by yourself and
use. The *.so files should not be part of the github repository since it is
platform dependent.

**Comment by haileeshen** [comment]
Thanks for your quick reply.
Can you please share the information of R libraries version should be used with me?

**Comment by kaichop** [comment]
I do not have the exact information but using the latest version should be
fine, assuming that the latest version is backward-compatible. So I think
you can perhaps just try download the source code and compile from there
(assuming that an ARM version of R is already available, you can just
'install.packages' to install all these automatically). I do not have
experience on ARM server to advise this more; if you can succeed then it
would be great if you can share the experience.
Please note that the R libraries are not needed for Phenolyzer. They are
useful for generating the plots, but not the gene prioritization itself.

**Comment by haileeshen** [comment]
Hello Kai,
Useful information.
Sure I will share the process when I completed this project.
And can you talk about other 2 libraries :) -- slam.so and wordcloud.so
or if them also parts of R libraries?
Haile ~

**Comment by Liu-Richard** [comment]
I download the Rcpp sourcecode(https://cran.r-project.org/src/contrib/Rcpp_1.0.2.tar.gz), but donnt know how to generate Rcpp.so from README. anybody knows how to build Rcpp to generate Rcpp.so for aarch64? because   external/Rcpp/libs/Rcpp.so(also  slam.so and wordcloud.so)  in phenolyzer is a X86_64 base， and my linux server is aarch64.
very appreciate if somebody could help

**Comment by haileeshen** [comment]
hello guys, 
Here is one easy way to replace the native libraries from X86 format in the package to Aarch64 one, we dont need to find source for the 3 libraries:
1. install R
```
#wget https://cran.r-project.org/src/base/R-3/R-3.6.1.tar.gz
#tar zxf R-3.6.1.tar.gz
#cd R-3.6.1/
#./configure --with-readline=no --with-x=no
#make
#make install
```

2. Install BioManager in R
```
>if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
```

3. Install Rcpp, slam and wordcloud
```
> BiocManager::install("Rcpp")
> BiocManager::install("slam")
> BiocManager::install("wordcloud")
```

4. find out the libraries come from installing the 3 Apps, then cp them to the path where the x86 libraries storing ,and replace them.

That's it~

**Comment by Liu-Richard** [comment]
good！thanks
