### ISSUE TITLE
Script used for precalculations?

### ISSUE THREAD

**Issue by sgfin** [WGLab/phenolyzer#14]
Hello,

My apologies if I missed it in the repo, but could you point me to the script that was used to compute and zip the precalculated expansions and scores?  I'm planning to use a tweaked version of the underlying databases and was hoping to re-pre-calculate the zip files.

Thank you very much,
Sam

**Comment by kaichop** [comment]
This issue was never addressed. The zip file contains pre-calculated scores, and these are simply created by running phenolyzer on each HPO term, one by one. I do not remember anything tricky here, really just run each term as input, then zip the file.
